version: '3.9'

services:
  api:
    build:
      context: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/var/app/'
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    stdin_open: true
  db:
    image: "postgres:13-alpine"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=conduit
      - POSTGRES_PASSWORD=abc
    ports:
      - '5432:5432'
  newman:
    build:
      context: ./spec/newman/
    depends_on:
      - api

volumes:
  pg-data:
